name: p4env
channels:
  - psi4/label/dev
  - intel
  - defaults
dependencies:
  - python=3.9
  - psi4
  - eigen
  - pybind11
  - icc_rt
  - dpcpp-cpp-rt
  - mkl-dpcpp
  - libclang
  - blas
  - numpy
  - scipy
  - fmt
  - opt_einsum
  - threadpoolctl
